### ISSUE TITLE
Crash in Arclight - Forge 1.19.2

### ISSUE THREAD

**Issue by XY-chenm** [Luke100000/ImmersiveArmors#108]
Hello！It may be your mod or Arclight's problem. I'm not sure about that,so I come here and issue.
There is a crash.

```
——————————————————————————
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method immersiveArmors$modifyArgs(F)F in immersive_armors.mixins.json:MixinLivingEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap immersive_armors-common-refmap.json
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
        ... 41 more
————————————————————
```
emmm,wasting your precious time and seeing what went wrong? (I'm pretty poor at coding)

**Comment by Luke100000** [comment]
Please stop using bukkit implementations, they are extremely aggressive :(

Basically: Arclight rips out stuff I (and potentially other modders) need

**Comment by Luke100000** [comment]
I believe this should be the issue in this case: https://github.com/IzzelAliz/Arclight/blob/1.19/arclight-common/src/main/java/io/izzel/arclight/common/mixin/core/world/entity/LivingEntityMixin.java#L511

**Comment by XY-chenm** [comment]
ah, tk u
i will tell these to the Arclight's auther.
