### ISSUE TITLE
Server crash while wearing wither chestplate

### ISSUE THREAD

**Issue by marianyp** [Luke100000/ImmersiveArmors#54]
Immersive Armors - 1.4.2 Fabric

```
 net.minecraft.class_148: Ticking entity
10.10 01:18:46 [Server] INFO at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
10.10 01:18:46 [Server] INFO Caused by: java.lang.ClassCastException: class net.minecraft.class_1667 cannot be cast to class net.minecraft.class_1309 (net.minecraft.class_1667 and net.minecraft.class_1309 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3159c4b8)
10.10 01:18:46 [Server] INFO at immersive_armors.armorEffects.WitherArmorEffect.applyArmorToDamage(WitherArmorEffect.java:36) ~[immersive_armors-1.4.2.jar:?]
10.10 01:18:46 [Server] INFO at immersive_armors.item.ExtendedArmorItem.applyArmorToDamage(ExtendedArmorItem.java:92) ~[immersive_armors-1.4.2.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.class_1309.apply(class_1309.java:28612) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.class_1309.modify$dgj000$redirectApplyDamage(class_1309.java:28646) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.class_1309.method_5643(class_1309.java:1126) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.class_1657.method_5643(class_1657.java:952) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.class_3222.method_5643(class_3222.java:713) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.class_1665.method_7454(class_1665.java:373) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.class_1676.method_7488(class_1676.java:149) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.class_1665.method_5773(class_1665.java:226) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.class_1667.method_5773(class_1667.java:104) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.class_3218.method_18762(class_3218.java:712) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.class_1937.method_18472(class_1937.java:466) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.class_3218.method_31420(class_3218.java:371) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.class_3218.method_18765(class_3218.java:339) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[server-intermediary.jar:?]
10.10 01:18:46 [Server] INFO ... 5 more
```

Got this error playing on my server. A player had lava dispensed on them while wearing a wither chestplate. Possibly caused by that.

**Comment by Ampflower** [comment]
I should note, this has also been reproduced by a fireball hitting you as the originating blaze despawned.

**Comment by Ampflower** [comment]
As this crash is major enough (*stops the server*), I'll be taking the time to go ahead and create a PR to fix this.

**Comment by Ampflower** [comment]
I do have to ask real quick: Is the fire immune check intentional here? https://github.com/KJP12/ImmersiveArmors/blob/d01883dd706451dc974f5f74d414893243e65c52/common/src/main/java/immersive_armors/armorEffects/WitherArmorEffect.java#L35

Fire immunity doesn't correspond to wither immunity that I know of.

**Comment by Luke100000** [comment]
Awesome, thanks! I will try to merge and push asap. Yes, the fire immunity is a copy pasta error from the robe, as they inflict fire damage, thanks for noticing!
