### ISSUE TITLE
Crashing when creating new wooden breastplate at workbench.

### ISSUE THREAD

**Issue by thetaprime1** [Luke100000/ImmersiveArmors#59]
The is on Fabric 1.19.2.

java.lang.NoSuchMethodError: 'net.minecraft.class_5250 net.minecraft.class_2588.method_27692(net.minecraft.class_124)'
	at immersive_armors.armorEffects.ArrowBlockArmorEffect.appendTooltip(ArrowBlockArmorEffect.java:36)
	at immersive_armors.item.ExtendedArmorItem.method_7851(ExtendedArmorItem.java:71)
	at net.minecraft.class_1799.method_7950(class_1799.java:699)
	at net.minecraft.class_437.method_25408(class_437.java:181)
	at net.minecraft.class_437.method_25409(class_437.java:168)
	at net.minecraft.class_465.method_2380(class_465.java:189)
	at net.minecraft.class_479.method_25394(class_479.java:68)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Luke100000** [comment]
Please also provide Minecraft and Fabric version

**Comment by Luke100000** [comment]
1.19.2 is no longer supported, I hope the error won't happen again in 1.19.3
