### ISSUE TITLE
Immersive Armor Crash

### ISSUE THREAD

**Issue by Laine-Steel** [Luke100000/ImmersiveArmors#81]
Whenever I go to boot up medieval minecraft in 1.19.2 v15.5, the modpack crashes due to immersive armor. Is there anyway to fix this issue

**Comment by Luke100000** [comment]
Log please!

**Comment by RaidyTM209** [comment]
I encountered the same problem when starting the server on the Arklight kernel.
console log
```
C:\Users\user\Desktop\RaaWORLD>java -Xms512M -Xmx4096M -jar arc.jar nogui
Применяется локализация ru_ru с откатом на zh_cn
[21:36:27 INFO] [Arclight]:

       ___           ___     __   /\
      /   | ________/ (_)__ / /  / /
     / /| |/ __/ __/ / / _ / _ \/__/
    / ___ / / / /_/ / / / / // / /
   /_/  |/_/  \__/_/_/\_ /_//_/ /
                     /__/     \/

    Версия 角 / arclight-1.19.2-1.0.1-0550c6cd
    Дата сборки 2022-12-09 06:14:54

[21:36:27 INFO] [c.m.m.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 43.2.0, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, nogui]
[21:36:27 INFO] [c.m.m.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.6 by Eclipse Adoptium; OS Windows 11 arch amd64 version 10.0
[21:36:28 INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/RaidyTM/Desktop/RaaWORLD/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2396!/ Service=ModLauncher Env=SERVER
[21:36:29 WARN]: Mod file C:\Users\RaidyTM\Desktop\RaaWORLD\libraries\net\minecraftforge\fmlcore\1.19.2-43.2.0\fmlcore-1.19.2-43.2.0.jar is missing mods.toml file
[21:36:29 WARN]: Mod file C:\Users\RaidyTM\Desktop\RaaWORLD\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.2.0\javafmllanguage-1.19.2-43.2.0.jar is missing mods.toml file
[21:36:29 WARN]: Mod file C:\Users\RaidyTM\Desktop\RaaWORLD\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.2.0\lowcodelanguage-1.19.2-43.2.0.jar is missing mods.toml file
[21:36:29 WARN]: Mod file C:\Users\RaidyTM\Desktop\RaaWORLD\libraries\net\minecraftforge\mclanguage\1.19.2-43.2.0\mclanguage-1.19.2-43.2.0.jar is missing mods.toml file
[21:36:29 INFO]: No dependencies to load found. Skipping!
[21:36:31 INFO] [mixin]: Compatibility level set to JAVA_17
[21:36:31 ERROR] [mixin]: Mixin config illuminations.mixins.json does not specify "minVersion" property
[21:36:31 INFO] [mixin]: Successfully loaded Mixin Connector [com.sonicether.soundphysics.MixinConnector]
[21:36:31 INFO] [mixin]: Successfully loaded Mixin Connector [io.izzel.arclight.common.mod.ArclightConnector]
[21:36:31 INFO] [Arclight]: Основной миксин Arclight добавлен.
[21:36:31 INFO] [Arclight]: Оптимизирующий миксин Arclight добавлен.
[21:36:31 INFO] [c.m.m.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments [nogui]
[21:36:31 WARN] [mixin]: Reference map 'projectvibrantjourneys.refmap.json' for projectvibrantjourneys.mixins.json could not be read. If this is a development environment you can ignore this message
[21:36:31 INFO] [fpsreducer]: OptiFine was NOT detected.
[21:36:31 INFO] [fpsreducer]: OptiFabric was NOT detected.
[Tough As Nails Transformer]: Transforming m_36399_ (F)V in net/minecraft/world/entity/player/Player
[Tough As Nails Transformer]: Successfully patched causeFoodExhaustion
[Serene Seasons Transformer]: Transforming m_47480_ (Lnet/minecraft/world/level/LevelReader;Lnet/minecraft/core/BlockPos;Z)Z in net/minecraft/world/level/biome/Biome
[Serene Seasons Transformer]: Patched 1 calls
[Serene Seasons Transformer]: Transforming m_47519_ (Lnet/minecraft/world/level/LevelReader;Lnet/minecraft/core/BlockPos;)Z in net/minecraft/world/level/biome/Biome
[Serene Seasons Transformer]: Successfully patched shouldSnow
[Serene Seasons Transformer]: Transforming m_8714_ (Lnet/minecraft/world/level/chunk/LevelChunk;I)V in net/minecraft/server/level/ServerLevel
[Serene Seasons Transformer]: Successfully patched tickChunk
[21:36:32 WARN] [mixin]: Error loading class: com/mojang/blaze3d/audio/Channel (java.lang.ClassNotFoundException: com.mojang.blaze3d.audio.Channel)
[21:36:32 WARN] [mixin]: @Mixin target com.mojang.blaze3d.audio.Channel was not found assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ChannelAccessor
[Serene Seasons Transformer]: Transforming m_8107_ ()V in net/minecraft/world/entity/animal/SnowGolem
[Serene Seasons Transformer]: Patched 1 calls
[Tough As Nails Transformer]: Transforming m_38710_ (Lnet/minecraft/world/entity/player/Player;)V in net/minecraft/world/food/FoodData
[Tough As Nails Transformer]: Successfully patched tick
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at MC-BOOTSTRAP/arclight.boot/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:41)
        at MC-BOOTSTRAP/arclight.boot/io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:12)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23)
        at io.izzel.arclight.server.Launcher.main(Launcher.java:18)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.0/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 15 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at TRANSFORMER/forge@43.2.0/net.minecraftforge.registries.GameData.init(GameData.java:108)
        at TRANSFORMER/forge@43.2.0/net.minecraftforge.registries.GameData.<clinit>(GameData.java:93)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.core.Registry.forge(Registry.java:435)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.core.Registry.forge(Registry.java:419)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.core.Registry.<clinit>(Registry.java:186)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Bootstrap.m_135870_(BootstrapMixin.java:43)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Main.main(Main.java:110)
        ... 21 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method immersiveArmors$modifyArgs(F)F in immersive_armors.mixins.json:MixinLivingEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap immersive_armors-common-refmap.json
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
        ... 41 more
Fail to launch Arclight.
```

**Comment by Luke100000** [comment]
These damn bukkit implementations...
